---
# This playbook contains plays that will install and configure nginx web-server.

- name: install nginx package
  apt: pkg=nginx state=latest

# setup configuration scripts
- name: create "config-templates" directory for custom nginx configuration templates
  command: /bin/mkdir /etc/nginx/config-templates creates=/etc/nginx/config-templates

- name: copy over custom nginx configuration templates
  template: src=config-templates/{{ item }} dest=/etc/nginx/config-templates/{{ item }}
  with_items:
    - common
    - php
    - symfony-dev
    - symfony-prod
  notify: restart nginx

# setup CA Certificate
- name: create "ca-certificates" directory for dummy SSL certificate
  command: /bin/mkdir /etc/nginx/ca-certificates creates=/etc/nginx/ca-certificates

- name: copy over dummy SSL certificate
  template: src=ca-certificates/{{ item }} dest=/etc/nginx/ca-certificates/{{ item }}
  with_items:
    - dummy.crt
    - dummy.csr
    - dummy.key
  notify: restart nginx

- name: copy default site configuration and restart nginx
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
